#!/usr/bin/env ruby
# This file is the entry point for our CLI/the rest of the program
# It will be what is run when installed as a gem and access via shell
require 'bundler/setup'
require 'issuetracker'
